### ISSUE TITLE
Field contained the following invalid HTML tags in GUID

### ISSUE THREAD

**Issue by PanderMusubi** [kerrickstaley/genanki#121] opened 2023-07-21 12:40 UTC
**Description**
Field contained the following invalid HTML tags.

**To reproduce**
Use `guid` containing `<p8` e.g..

**Expected behavior**
HTML tags should not be checked for guid perhaps?

**Actual behavior**
Warming gets printed:

    ~/.local/lib/python3.10/site-packages/genanki/note.py:153: UserWarning: Field contained the following invalid HTML tags. Make sure you are calling html.escape() if your field data isn't already HTML-encoded: <p8{N2>
      warnings.warn("Field contained the following invalid HTML tags. Make sure you are calling html.escape() if"

**genanki version**
0.13.0

**Additional context**
Using pprint(self.fields[-1]) helps for debugging. These are valid values

    'mG!uQ0:Vaa'
    'phJgSa.0<A'
    'q-j%yoC$6t'
    'jME[c!LmuS'
    'uK6|=e8*BU'
    're?KG.[pR-'
    'F=6:v}NdTB'
    'd(nZ^NdjTO'
    'BAlO]`HJQg'
    'f.2v`3WgFR'
    'Dy(+X(BhdM'
    'm82/uZ.;[u'

This is an invalid value

    'Gt<p8{N2>Z'

**Comment by PanderMusubi** [comment] 2023-07-21 16:32
PS This occurred when using https://github.com/lukesmurray/markdown-anki-decks

**Comment by kerrickstaley** [comment] 2023-11-26 21:39
I was unable to reproduce this issue. Could you give a complete, minimal example that I can run to see the issue?

I added [this test](https://github.com/kerrickstaley/genanki/blob/0185006440dca3e4a4d70b2cde2b61cd1e4c3281/tests/test_note.py#L271) which I thought would reproduce the problem, but the test already passes without changing `genanki`'s code.

**Comment by kerrickstaley** [comment] 2023-12-29 21:53
Closing this issue for now; please re-open this if you are still seeing this problem!

**Closed by kerrickstaley** 2023-12-29 21:53 UTC
